spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ALEJANDRA
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true